@startuml
skinparam classAttributeIconSize 0
skinparam Shadowing true

skinparam class {
    ArrowColor Purple
    BackgroundColor Pink
    BorderColor Purple
}

skinparam note {
    BackgroundColor LightYellow
    BorderColor Purple
}

namespace vendedores #A9F5F2 {
    abstract class Vendedor {
        # puntos : int
        # nombre : String
        - categoria : String
        + {abstract} vender() : void
        + {abstract} calcularPuntos() : int
        + mostrarCategoria() : void
        - recategorizar() : void
    }

    note left
        0 <= pts < 20 → novatos
        20 <= pts <= 30 → aprendices
        30 < pts <= 40 → buenos
        40 < pts → maestros
    end note

    class Empleado extends Vendedor {
        - anioIngreso : Year
        + vender() : void
        + calcularPuntos() : int
        + conseguirAfiliado(afiliado : Afiliado) : void
        - calcularAntiguedadEnAnios() : int
    }

    class Afiliado extends Vendedor {
        + vender() : void
        + calcularPuntos() : int
    }

    Empleado "1" -> "*" Afiliado
}

@enduml